fixes issue #3

diff --git a/optv b/optv
--- a/optv
+++ b/optv
@@ -63,6 +63,7 @@ execute_command () {
     elif [ "$command" = "pull" ]
     # Repository code/data update
     then
+        cd "${CALLDIR}" || { echo "Could not cd to the script directory?!?" ; exit 1 ; }
         # Update main repository
         echo "Updating main"
         git pull
