Implement multiple commands execution
This allows to run

optv update publish

to download new files+merge/time align them+push the changes on the
git server

diff --git a/optv b/optv
--- a/optv
+++ b/optv
@@ -37,135 +37,161 @@ codedir () {
     echo "${CALLDIR}/OpenParliamentTV-Tools/optv/parliaments/$1"
 }
 
-command="$1"
+execute_command () {
+    command=$1
 
-if [ "$command" = "init" ]
-# Repository structure initialization
-then
-    for d in $REPOS
-    do
-        if [ ! -d "$d" ]
-        then
-            git clone "${REPOBASE}${d}.git"
-        fi
-    done
-elif [ "$command" = "pull" ]
-# Repository code/data update
-then
-    # Update main repository
-    echo "Updating main"
-    git pull
-
-    # Update all git repositories
-    for d in $REPOS
-    do
-        echo "Updating $d"
-        ( cd "$d" && git pull )
-    done
-elif [ "$command" = "status" ]
-# Repository status
-then
-    git status
-    for d in $REPOS
-    do
-        if [ -d "$d" ]
-        then
-            ( cd "$d" && git status )
-        else
-            echo "$d is not present - you should run init"
-        fi
-    done
-    # docker-compose ps
-elif [ "$command" = "check" ]
-# Checks
-then
-    # Check repositories/dependencies/etc
-    basic_check
-    retcode=$?
-    # Check that PARLIAMENTS defined code/data is here
-    for p in $PARLIAMENTS
-    do
-        for d in "$(datadir $p)" "$(codedir $p)"
+    if [ "$command" = "init" ]
+    # Repository structure initialization
+    then
+        for d in $REPOS
         do
             if [ ! -d "$d" ]
             then
-                echo "Parliament ${p} - missing ${d}"
-                retcode=1
+                git clone "${REPOBASE}${d}.git"
             fi
         done
-    done
-    # Check python modules
-    for module in aeneas yaml feedparser lxml spacy
-    do
-        python3 -c "import ${module}" > /dev/null 2>&1
-        if [ ! $? ]
-        then
-            retcode=1
-            echo "The python module ${module} is not present. Run 'python3 -m pip install -r OpenParliamentTV-Tools/requirements.txt' to install it."
-            if [ "${module}" = "aeneas" ]
-            then
-                echo "Note that it depends on python3-dev and espeak-dev (on Debian, you can install them with `sudo apt install python3-dev espeak-dev`)"
-            fi
-        fi
-    done
-    if [ $retcode ]
+    elif [ "$command" = "pull" ]
+    # Repository code/data update
     then
-        echo "All checks OK"
-    fi
-    exit $retcode
-elif [ "$command" = "update" ]
-# Data update
-then
-    for p in $PARLIAMENTS
-    do
-        cd "$(codedir $p)" || { echo "Could not cd to the $(codedir $p) directory?!?" ; exit 1 ; }
-        data="$(datadir $p)"
-        log "Updating data for $p into $data"
-        ./workflow.py --period=$PERIOD --retry-count=20 "$data" >> "${LOGFILE}" 2>&1
-    done
-elif [ "$command" = "align" ]
-# Do time align
-then
-    for p in $PARLIAMENTS
-    do
-        cd "$(codedir $p)" || { echo "Could not cd to the $(codedir $p) directory?!?" ; exit 1 ; }
-        data="$(datadir $p)"
-        log "Aligning data for $p into $data"
-        ./workflow.py --period=$PERIOD --retry-count=20 --no-download-original --align-sentences "$data" >> "${LOGFILE}" 2>&1
-    done
-elif [ "$command" = "fullupdate" ]
-# Do full update + time align + NER
-then
-    for p in $PARLIAMENTS
-    do
-        cd "$(codedir $p)" || { echo "Could not cd to the $(codedir $p) directory?!?" ; exit 1 ; }
-        data="$(datadir $p)"
-        log "Updating+aligning+NER data for $p into $data"
-        ./workflow.py --period=$PERIOD --retry-count=20 --align-sentences --extract-entities "$data" >> "${LOGFILE}" 2>&1
-    done
-elif [ "$command" = "publish" ]
-then
-    for p in $PARLIAMENTS
-    do
-        cd "$(datadir $p)" || { echo "Could not cd to the $(datadir $p) directory?!?" ; exit 1 ; }
-        git add original/media original/proceedings original/processed
-        git commit -m "optv publication on $(date -I)"
-        git push
-    done
-else
-    cat <<EOF
+        # Update main repository
+        echo "Updating main"
+        git pull
+
+        # Update all git repositories
+        for d in $REPOS
+        do
+            echo "Updating $d"
+            ( cd "$d" && git pull )
+        done
+    elif [ "$command" = "status" ]
+    # Repository status
+    then
+        git status
+        for d in $REPOS
+        do
+            if [ -d "$d" ]
+            then
+                ( cd "$d" && git status )
+            else
+                echo "$d is not present - you should run init"
+            fi
+        done
+        # docker-compose ps
+    elif [ "$command" = "check" ]
+    # Checks
+    then
+        # Check repositories/dependencies/etc
+        basic_check
+        retcode=$?
+        # Check that PARLIAMENTS defined code/data is here
+        for p in $PARLIAMENTS
+        do
+            for d in "$(datadir $p)" "$(codedir $p)"
+            do
+                if [ ! -d "$d" ]
+                then
+                    echo "Parliament ${p} - missing ${d}"
+                    retcode=1
+                fi
+            done
+        done
+        # Check python modules
+        for module in aeneas yaml feedparser lxml spacy
+        do
+            python3 -c "import ${module}" > /dev/null 2>&1
+            if [ ! $? ]
+            then
+                retcode=1
+                echo "The python module ${module} is not present. Run 'python3 -m pip install -r OpenParliamentTV-Tools/requirements.txt' to install it."
+                if [ "${module}" = "aeneas" ]
+                then
+                    echo "Note that it depends on python3-dev and espeak-dev (on Debian, you can install them with `sudo apt install python3-dev espeak-dev`)"
+                fi
+            fi
+        done
+        if [ $retcode ]
+        then
+            echo "All checks OK"
+        fi
+        exit $retcode
+    elif [ "$command" = "download" ]
+    # Download only
+    then
+        for p in $PARLIAMENTS
+        do
+            cd "$(codedir $p)" || { echo "Could not cd to the $(codedir $p) directory?!?" ; exit 1 ; }
+            data="$(datadir $p)"
+            log "Updating data for $p into $data"
+            ./workflow.py --period=$PERIOD --retry-count=20 "$data" >> "${LOGFILE}" 2>&1
+        done
+    elif [ "$command" = "update" ]
+    # Download + time-align
+    then
+        for p in $PARLIAMENTS
+        do
+            cd "$(codedir $p)" || { echo "Could not cd to the $(codedir $p) directory?!?" ; exit 1 ; }
+            data="$(datadir $p)"
+            log "Updating data for $p into $data"
+            ./workflow.py --period=$PERIOD --retry-count=20 --align-sentences "$data" >> "${LOGFILE}" 2>&1
+        done
+    elif [ "$command" = "align" ]
+    # Time align only without downloading first
+    then
+        for p in $PARLIAMENTS
+        do
+            cd "$(codedir $p)" || { echo "Could not cd to the $(codedir $p) directory?!?" ; exit 1 ; }
+            data="$(datadir $p)"
+            log "Aligning data for $p into $data"
+            ./workflow.py --period=$PERIOD --retry-count=20 --no-download-original --align-sentences "$data" >> "${LOGFILE}" 2>&1
+        done
+    elif [ "$command" = "fullupdate" ]
+    # Do full update + time align + NER
+    then
+        for p in $PARLIAMENTS
+        do
+            cd "$(codedir $p)" || { echo "Could not cd to the $(codedir $p) directory?!?" ; exit 1 ; }
+            data="$(datadir $p)"
+            log "Updating+aligning+NER data for $p into $data"
+            ./workflow.py --period=$PERIOD --retry-count=20 --align-sentences --extract-entities "$data" >> "${LOGFILE}" 2>&1
+        done
+    elif [ "$command" = "publish" ]
+    then
+        for p in $PARLIAMENTS
+        do
+            cd "$(datadir $p)" || { echo "Could not cd to the $(datadir $p) directory?!?" ; exit 1 ; }
+            git add original/media original/proceedings processed
+            git commit -m "optv publication on $(date -I)"
+            git push
+        done
+    else
+        cat <<EOF
 $0 - handle OpenParliamentTV services
 
-Syntax: optv command
+Syntax: optv command [...command]
 with command being
 
 check - check necessary dependencies/dir layout
 init - initialize repositories
 pull - update all git repositories
 status - status of docker containers and git repositories
-update - update parliament data
-align - time-align files that need it
+update - update parliament data (download + time-align)
+download - download parliament data (download media+proceedings)
+align - time-align files that need it (no download)
 fullupdate - do a full update+align+NER
 publish - publish new files to git server
 EOF
+        exit 1
+    fi
+}
+
+
+if [ -z "$*" ]
+then
+    # This will exit
+    execute_command help
 fi
+
+for command in "$@"
+do
+    execute_command "$command"
+done
